name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Clone vcpkg
      run: git clone https://github.com/Microsoft/vcpkg.git

    - name: Bootstrap vcpkg
      run: ./bootstrap-vcpkg.bat
      shell: cmd
      working-directory: vcpkg

    - name: Install dependencies
      run: |
        ./vcpkg/vcpkg install nlohmann-json:x64-windows
        ./vcpkg/vcpkg install catch2:x64-windows
        ./vcpkg/vcpkg install cli11:x64-windows

    - name: Set up CMake
      uses: lukka/get-cmake@v3.24.3

    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake"

    - name: Build
      run: cmake --build build --config Release

    - name: Run tests
      run: ctest --test-dir build -C Release --output-on-failure
